dist: xenial
sudo: required

language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - pytest --cov -n 2 tests/

after_success:
  - codecov
