dist: xenial
sudo: required

language: python
python:
  - "3.7"

install:
  - pip install -e .
  - pip install --upgrade -r requirements-dev.txt
  - pip install codecov

script:
  - pytest --cov -n 2 tests/

after_success:
  - codecov
